### ISSUE TITLE
Cow

### ISSUE THREAD

**Issue by hugomano** [damoebius/Cow4#1]
Est-ce que le poulet va bouger (surement vu qu'il y a 3 IA) ? Si oui, c'est prévu pour quand ?

**Comment by damoebius** [comment]
Demain normalement

**Comment by s1mak** [comment]
Cool, on attend la prochaine release alors pour poser nos questions :)

**Comment by damoebius** [comment]
C'est fait,
npm update ou npm install codeofwar pour ceux qui n'ont pas encore installé le projet
