### ISSUE TITLE
souci de chemin relatif

### ISSUE THREAD

**Issue by 1000i100** [damoebius/Cow4#10]
Si je lance le serveur depuis un autre dossier que celui prévu :

```
node node_modules/codeofwar/js/release/Server.js
```

au lieu de : 

```
cd node_modules/codeofwar/
node js/release/Server.js
```

j'obtien ce message d'erreur au lieux de la page souhaité.

```
Error: ENOENT, stat 'c:\[...]\coq-of-war\server\index.html'
   at Error (native) 
```

N'auriez-vous pas moyen de faciliter le lancement distant pour pouvoir lancer le serveur en même temps que le client pour les test ?

**Comment by damoebius** [comment]
C'est vrai, je vais corriger ça

**Comment by damoebius** [comment]
tu peux tester la nouvelle version 1.0.4 et me dire si c'est bon ?
