### ISSUE TITLE
Frontend qui tente charger Localhost

### ISSUE THREAD

**Issue by fabienfleureau** [damoebius/Cow4#11]
Sur la page d'accueil il y a une tentative de connection vers
http://localhost:3000
Cela ne fonctionne pas si le serveur est installé sur une machine distante.

**Comment by damoebius** [comment]
Oui c'est vrai, je vais corriger ça. Il y a un pull request qui devrait le corriger : https://github.com/damoebius/Cow4/pull/9

**Comment by damoebius** [comment]
c bon ?

**Comment by fabienfleureau** [comment]
Il y a encore des références à localhost dans le code (Frontend.js). Je ne sais pas si c'est corrigé, j'utilise une version custom où j'ai remplacé toutes ces références.

**Comment by wpottier** [comment]
Effectivement il y en à encore.
- src/com/tamina/cow4/view/PlayView.hx 
- release/js/release/Frontend.js 
- release/server/js/Frontend.js

**Comment by damoebius** [comment]
Bon normalement c'est bon, il n'y a plus de localhost et on peut lancer l'IA de demo vers un autre serveur
