### ISSUE TITLE
Position du poulet

### ISSUE THREAD

**Issue by AlphaDev-Fr** [damoebius/Cow4#13]
Bonjour,

La position du poulet renvoyé par le serveur n'est pas bonne.
Par exemple les mouvements du poulet sur les 1er tour :

| Renvoyé par le serveur | Vus sur la carte |
| --- | --- |
| [x:12y:12] | [x:12y:12] |
| [x:12y:12] | [x:12y:12] |
| **[x:10y:12]** | **[x:11y:12]** |
| [x:10y:12] | [x:10y:12] |
| [x:9y:12] | [x:19y:12] |

J'ai noté le problème à chaque fois que le poulet est sur une intersection.

**Comment by damoebius** [comment]
Mmm, étrange.  Je vais rajouter des logs et voir si je reproduis le bug

**Comment by damoebius** [comment]
Je viens de tester sur une partie et je n'ai pas reproduit le bug. Tu peux tester avec la nouvelle version de code of war et me donner un cas de test ? (position des IA)

**Comment by AlphaDev-Fr** [comment]
le déplacement à l'air OK maintenant je ferme le bug.
