### ISSUE TITLE
IA du coq incohérente?

### ISSUE THREAD

**Issue by wpottier** [damoebius/Cow4#14]
Hello,
En effectuant quelques test, je constate que le coq un fois arrivé à une intersection, fait demi-tour et reviens droit sur mon joueur. Est-ce normal?  D'après la description de l'IA du coq dans le README je dirais que non. D'autant que la deuxième IA se trouve dans la même direction que la première.

De plus je me retrouve dans un cas de fin de partie en erreur ou le serveur s'arrête car le coq essai de venir sur la case ou se trouve mon IA ("SheepIA : la case ciblée est déjà occupée"). ça me semble surprenant comme comportement.

![capture d ecran 2015-10-07 a 14 42 54](https://cloud.githubusercontent.com/assets/361974/10337689/bb2019ce-6d01-11e5-8ef7-d1e4cd4f260c.png)

**Comment by damoebius** [comment]
Effectivement, je vais corriger ça

**Comment by damoebius** [comment]
Normalement l'IA ne pourra plus aller sur une case occupée. Tu me confirmes ?

**Comment by wpottier** [comment]
Effectivement le coq ne me saute plus dessus. Par contre il se bloque complètement plutôt que de chercher à se sauver. c'est normal? 
D'après le code de son IA il ne bouge plus comme il a une targetCell il ne cherche pas à trouver une autre direction. 

Après c'est peut-être voulu comme ça ;-)

**Comment by damoebius** [comment]
Oui j'ai fais vite, pour eviter de provoquer une condition de fin de
partie non prévue. 

Mais je vais faire quelque chose pour la rendre moins bete. 

Le 09.10.2015 15:28, William POTTIER a écrit : 

> Effectivement le coq ne me saute plus dessus. Par contre il se bloque complètement plutôt que de chercher à se sauver. c'est normal? 
> D'après le code de son IA il ne bouge plus comme il a une targetCell il ne cherche pas à trouver une autre direction. 
> 
> Après c'est peut-être voulu comme ça ;-) 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/damoebius/Cow4/issues/14#issuecomment-146871728

**Comment by damoebius** [comment]
Je viens de publier une nouvelle version qui permet de definir la position de départ des IA.
Du coup si vous rencontrez une anomalie du comportement du poulet, vous pouvez ouvrir une nouvelle issue avec les coodonnées à utiliser pour reproduire l'anomalie.
Ca va grandement m'aider à debuguer l'IA mais ça devrait aussi vous etre tres utile pour améliorer la votre :)

**Comment by fabienfleureau** [comment]
Salut,
Je reviens avec un cas ou le poulet fait demi tour pour foncer vers le joueur alors qu'il devrait s'en éloigner.
La position du poulet: [12,8]
La position du joueur 1: [9,10]

Le coup d'après le poulet va en [11,8] alors qu'il devrait aller en [12,9]
![positions](https://cloud.githubusercontent.com/assets/3874760/10591834/ac24f596-76b8-11e5-84e8-3cf93615ee87.jpg)

**Comment by damoebius** [comment]
Et joueur 2 ?
Le 19 oct. 2015 23:28, Fabien Fleureau notifications@github.com a écrit :Salut,
Je reviens avec un cas ou le poulet fait demi tour pour foncer vers le joueur alors qu'il devrait s'en éloigner.
La position du poulet: [12,8]
La position du joueur 1: [9,10]

Le coup d'après le poulet va en [11,8] alors qu'il devrait aller en [12,9]

**Comment by fabienfleureau** [comment]
Joueur 2 : [24;24]

**Comment by damoebius** [comment]
Super, j'ai pu reproduire le bug. Le probleme semble venir du PathFinder interne au serveur.

**Comment by dmouton** [comment]
Raaaa c'est bon, j'ai trouvé et corrigé ça avec la release 1.07. Tu me dis si c'est mieux ?

**Comment by JohnGullSton** [comment]
J'avais deux cas similaires qui sont résolus par ta correction.
