### ISSUE TITLE
Quelle est la durée d'invisibilité ?

### ISSUE THREAD

**Issue by JohnGullSton** [damoebius/Cow4#16]
Salut,

La version 1.0.4 a changé la durée d'invisibilité de 42 à 10 au niveau des constantes.
Par contre le README est resté à 42 tours.

Est-ce un oubli dans le README ou une erreur dans les constantes ?

**Comment by damoebius** [comment]
C'est un oubli dans le readme, 42 tours c'etait trop puissant.
