### ISSUE TITLE
Poulet demarre un tour apres

### ISSUE THREAD

**Issue by pacwoodson** [damoebius/Cow4#17]
Est-ce moi qui compte mal, ou le poulet ne fait rien au premier tour et commence à se deplacer au deuxieme ?

**Comment by damoebius** [comment]
Il est le dernier à jouer, je n'ai pas constaté de retard. Tu pourrais faire un screencast qu'on regarde ensemble ?

**Comment by damoebius** [comment]
C'est vrai, ça sera corrigé dans la prochaine version

**Comment by dmouton** [comment]
C'est bon. Je viens de publier une nouvelle release 1.07. Tu me dis si c'est bon ?
