### ISSUE TITLE
404 on ia_sprite

### ISSUE THREAD

**Issue by JbIPS** [damoebius/Cow4#2]
ia_sprite URL is missing `images` prefix here: https://github.com/damoebius/Cow4/blob/master/release/server/js/Frontend.js#L1460

**Comment by damoebius** [comment]
Tu dois spécifier un profil dans ton message d'authentification : https://github.com/damoebius/Cow4/blob/master/src/com/tamina/cow4/socket/message/Authenticate.hx

J'ai mis à jour la doc.

Dis moi si ça fonctionne

**Comment by JbIPS** [comment]
Ok, j’étais pas parti sur le bon repo, moi j'avais pris https://github.com/damoebius/Cow4_SDK qui n'a pas l'air d’être à jour.
Je retente avec l'autre !

**Comment by JbIPS** [comment]
Ça marche bien, par contre ton enum de profil ne correspond pas à Sorcier/Nain/Chevalier. Tu peux donner une correspondance stp ?
Merci

**Comment by damoebius** [comment]
Tu utilises la version dispo sur npm ou celle de github ?
Parceque pour moi l'enum est bonne.
Qu'est-ce qu'il te fait croire que ce n'est pas le cas ?

**Comment by JbIPS** [comment]
J'ai suivi le lien de la doc qui pointe vers https://github.com/damoebius/Cow4/blob/master/src/com/tamina/cow4/model/Profil.hx (Tech wizard, master of coins, hand of the king)

**Comment by damoebius** [comment]
Ben c'est bon. C'est quoi le pb alors ?

**Comment by JbIPS** [comment]
Ben, tu parles d'un nain, d'un sorcier et d'un chevalier dans la doc o.O

**Comment by damoebius** [comment]
Ah oui c'est vrai :)
Je corrige ça

**Comment by JbIPS** [comment]
Merci :)
