### ISSUE TITLE
Timeout sur un envoi de 1sec

### ISSUE THREAD

**Issue by AlphaDev-Fr** [damoebius/Cow4#21]
Je lance le serveur avec les options suivantes : 
js/release/Server.js -p1_pos 8,13 -p2_pos 2,18 -c_pos 4,17
Le p2 ne bouge pas, il envoie des ordres vides : 
result : {"type":"turnResult","actions":[]}#end#
Le p1 envoie : 

Turn 0 in time 1133ms
result : {"type":"turnResult","actions":[{"type":"move","target":1424090482567}]}#end#

Turn 1 in time 1001ms
order [Move to [x:9y:14]] 
result : {"type":"turnResult","actions":[{"type":"move","target":1424090482568}]}#end#

Turn 2 in time 1000ms
order [Move to [x:10y:14]] 
result : {"type":"turnResult","actions":[{"type":"move","target":1424090482569}]}#end#

Turn 3 in time 1001ms
order [Move to [x:10y:14]] 
result : {"type":"turnResult","actions":[{"type":"move","target":1424090482569}]}#end#

Le délai entre les ordres est de 1sec environ et pourtant je me prend un TIMEOUT
1446159053120 : TIMEOUT : next ia turn

PS : quand je force p2 à mettre 1 sec à répondre j'ai plus de problème.

**Comment by damoebius** [comment]
Mmm, le timeout est réglé à 2sec et tiens compte en plus du temps
consommé par la transaction. Tu testes en local ? 

Le 30.10.2015 00:01, AlphaDev-Fr a écrit : 

> Je lance le serveur avec les options suivantes : 
> js/release/Server.js -p1_pos 8,13 -p2_pos 2,18 -c_pos 4,17
> Le p2 ne bouge pas, il envoie des ordres vides : 
> result : {"type":"turnResult","actions":[]}#end#
> Le p1 envoie : 
> 
> Turn 0 in time 1133ms
> result : {"type":"turnResult","actions":[{"type":"move","target":1424090482567}]}#end# 
> 
> Turn 1 in time 1001ms
> order [Move to [x:9y:14]] 
> result : {"type":"turnResult","actions":[{"type":"move","target":1424090482568}]}#end# 
> 
> Turn 2 in time 1000ms
> order [Move to [x:10y:14]] 
> result : {"type":"turnResult","actions":[{"type":"move","target":1424090482569}]}#end# 
> 
> Turn 3 in time 1001ms
> order [Move to [x:10y:14]] 
> result : {"type":"turnResult","actions":[{"type":"move","target":1424090482569}]}#end# 
> 
> Le délai entre les ordres est de 1sec environ et pourtant je me prend un TIMEOUT
> 1446159053120 : TIMEOUT : next ia turn 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/damoebius/Cow4/issues/21

**Comment by AlphaDev-Fr** [comment]
ok j'avais un bug, je ferme l'issue
