### ISSUE TITLE
Fonctionnement de l'API

### ISSUE THREAD

**Issue by show0k** [damoebius/Cow4#22]
Bonjour,
Je l'exemple donné dans le README avec le serveur en local avec curl et je n'arrive pas à m'authentifier.
On est d'accord que selon ce qui est expliqué 

``` bash
curl -H "Content-Type: application/json" -X POST -d '{"type":"authenticate","name":"monIa","avatar":"http://monsite/monavatar.jpg","token":"yourtokenifone","profil":1}#end#' http://localhost:8127
```

devrait me permettre de m'authentifier.

Pourtant j'ai aucune réponse du serveur et j'ai le message :

```
[socket server] new connection 
[client proxy] impossible de parser le message json : Unexpected token P
```

Autre question pourquoi séparer les messages par une chaine #end# ? Une seule requête suffit pour poster toute les infos, non ?

**Comment by show0k** [comment]
J'ai trouvé le problème en regardant le contenu des paquets. Le serveur JS lit de _façon brute_ le paquet qu'il reçoit, et interprète les entêtes comme des données, d'où le besoin du "#end#". 
Le serveur communique avec des sockets bruts, et non pas des requêtes HTTP. Quel est l’intérêt de se passer d'HTTP ?

**Comment by damoebius** [comment]
C'est parceque ce n'est pas une connection HTTP qu'il faut établir, mais Socket !
Sur une socket les données sont streamées, il faut donc un tag pour séparer les paquets.
