### ISSUE TITLE
Lien vers la doc de l'api mort

### ISSUE THREAD

**Issue by pacwoodson** [damoebius/Cow4#5]
Bonjour à tous, 

Depuis la mise a jour du site, le lien vers la doc de l'api est mort : http://www.codeofwar.net/api/modules/Server.html

Je ne sais pas si elle a évolué depuis la derniere fois que j'y suis allé, mais je ne sais toujours pas quelle est le format pour envoyer des actions.
Serait-il possible d'ajouter au readme un exemple d'action ?

```
{
    "type":"turnResult",
    "ia":{},
    "actions":[
        {} // Exemple d'action
    ]
}
```

Merci beaucoup :)

**Comment by damoebius** [comment]
OK j'ai mis à jour la doc avec le bon lien vers l'api.
Pour t'inspirer, tu peux regarder les sources de l'AI de demo https://github.com/damoebius/Cow4/blob/master/src/com/tamina/cow4/IADemoApp.hx
Tu verras que dans processTurn, il peuple son TurnResult avec des MoveOrder

Dans la doc actions est une liste de TurnAction.
https://github.com/damoebius/Cow4/blob/master/src/com/tamina/cow4/model/TurnAction.hx
Un TurnAction est un objet avec une proriété type de type Action
https://github.com/damoebius/Cow4/blob/master/src/com/tamina/cow4/model/Action.hx

``` javascript
{
     "type":"move"
}
```

Un MoveOrder est un TurnAction avec une info en plus, l'id de la destination
https://github.com/damoebius/Cow4/blob/master/src/com/tamina/cow4/socket/message/order/MoveOrder.hx

``` javascript
{
     "type":"move",
     "target":4581686168
}
```
