### ISSUE TITLE
Manque des fichiers pour le serveur

### ISSUE THREAD

**Issue by pacwoodson** [damoebius/Cow4#6]
Hello, 

Depuis la mise a jour de ce weekend il y a deux petits soucis avec le serveur.

Il manque le fichier `codeofwar/server/js/easeljs-0.7.1.min.js` 

Et le fichier `codeofwar/server/img/gameMap.png` est dans le dossier `images` au lieu de `img`.

Merci ;)

**Comment by damoebius** [comment]
Normalement c'est corrigé, tu confirmes ?

**Comment by pacwoodson** [comment]
Nop, tu as mis easeljs dans codeofwar/release/, alors qu'il est cherché dans codeofwar/server/js/

**Comment by damoebius** [comment]
Heuuuu tu as  bien installé le jeu avec un npm install codeofwar ?

**Comment by pacwoodson** [comment]
ouep, et ça fonctionne bien quand je copie ce fichier dans `codeofwar/server/js` au lieu de `codeofwar/js`

**Comment by damoebius** [comment]
arg

**Comment by damoebius** [comment]
je viens de faire une nouvelle maj, la 1.0.3. Dis moi que ça marche maintenant !

**Comment by pacwoodson** [comment]
Niquel :)

**Comment by pacwoodson** [comment]
En revanche, rien à voir, mais je suis pas sur que tu aies compilé les commit de la 1.0.2, enfin peut etre que c'est volontaire

**Comment by damoebius** [comment]
Oui c'est parcequ'ils ne sont pas pret
