### ISSUE TITLE
Fin du jeu

### ISSUE THREAD

**Issue by pacwoodson** [damoebius/Cow4#7]
Rebonjour, je suis bien parti pour vous embeter un max :)

Quand un des joueurs attrape le poulet, ou que le jeu se termine de manière generale, rien n'est envoyé aux IA pour leur dire ? J'ai l'impression qu'il ne se passe pas grand chose ...

**Comment by damoebius** [comment]
Mmm, rien n'est envoyé aux IA. Il y a un message envoyé au site qui affiche un (tout petit) message.
Tu peux aussi regardé la console du serveur

**Comment by pacwoodson** [comment]
Ca pourrait être sympa d'avoir un retour un peu plus clair sur l'interface, et un message aux IA pour les stopper.

**Comment by damoebius** [comment]
Absolument, ça sera l'objet de la prochaine version.
