### ISSUE TITLE
Les profils ne correspondent pas

### ISSUE THREAD

**Issue by borisschapira** [damoebius/Cow4#8]
Dans la doc : MASTER_OF_COINS, TECH_WIZARD et HAND_OF_THE_KING.
Mais sur le site : Nain, Alchimiste et Elfe.

J'imagine que ça ne change rien à leur "pouvoir", mais je signale tout de même.

**Comment by damoebius** [comment]
Oui c'est vrai, il y a le nom commercial et le nom technique.
Pour la correspondance, tout bon roliste aura compris que : 
Nain -> MASTER_OF_COINS
Alchimiste -> TECH_WIZARD
Elfe -> HAND_OF_THE_KING
;)
